### ISSUE TITLE
fingerprint changes when browser zooms in or out

### ISSUE THREAD

**Issue by cxytomo** [fingerprintjs/blog-nojs-fingerprint-demo#3]
## Basic Info
Platform: MacBook Air M1 chip
OS: MacOS Monterey Version 12.1 (21C52)
Browser tested:  Chrome, Safari, Firefox

### 100%
<img width="578" alt="image" src="https://user-images.githubusercontent.com/2089688/158516116-a45c8c31-a86d-4f8e-84ba-97ba08f1b40c.png">

### 125%
<img width="678" alt="image" src="https://user-images.githubusercontent.com/2089688/158517469-8ce8fc5b-cdd7-4247-8037-7b9908fb3acc.png">

## Conclusion
Chrome and Firefox's fingerprint changes, while Safari's stay the same no matter zoom in or out. Fingerprint changes because device-pixel-ratio changes.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/2089688/158516830-1bf78a8e-40b3-4b87-81e2-4fe3bc52fe07.png">

**Comment by Valve** [comment]
@cxytomo thanks for letting us know about this issue.
This is a demo for a blog article, not a product that we maintain.
We won't be making further contributions into this code, as it was intended only for demonstration purposes.
Apologies for the inconvenience
